### PR TITLE
brew_release.dsl: build bottles for catalina

### PR DESCRIPTION
**Pull request by scpeters**
We already have a build machine with catalina: https://build.osrfoundation.org/computer/mac-t1000.catalina/

I'll test this before merging.

### CODE REVIEW

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/_dsl_brew_release/530/) https://build.osrfoundation.org/job/_dsl_brew_release/530/

**Comment by chapulina** [comment]
Is there a way to choose the macOS version according to the library / version? So we build Citadel / Dome for Mojave, and Edifice for Catalina?

**Comment by scpeters** [comment]
building a catalina bottle for https://github.com/osrf/homebrew-simulation/pull/1309

[Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_catalina/237/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/237/label=osx_catalina/

**Comment by scpeters** [comment]
> Is there a way to choose the macOS version according to the library / version? So we build Citadel / Dome for Mojave, and Edifice for Catalina?

in terms of bottle building, we can specify the minimum version required in the homebrew formulae, and it will build bottles for all supported versions for which we have build machines

in terms of CI, we could set different labels for release branch jobs according to the ignition collection so they would run on the proper machine, but it wouldn't really be feasible for the `ci-pr_any` jobs. I would recommend just using catalina for pull request jobs unless @j-rivero has a better idea

**Comment by scpeters** [comment]
> building a catalina bottle for [osrf/homebrew-simulation#1309](https://github.com/osrf/homebrew-simulation/pull/1309)
> 
> [Build Status](https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/label=osx_catalina/237/) https://build.osrfoundation.org/job/generic-release-homebrew_triggered_bottle_builder/237/label=osx_catalina/

test build succeeded

**Comment by chapulina** [comment]
> I would recommend just using catalina for pull request jobs 

That means we would risk breaking Mojave support for Citadel and Dome users, right? I guess that's the same situation we'd be in with respect to Bionic if we changed our PR jobs to Focal. Maybe that's something we can compensate for with GitHub actions.

**Comment by scpeters** [comment]
> > I would recommend just using catalina for pull request jobs
> 
> That means we would risk breaking Mojave support for Citadel and Dome users, right? I guess that's the same situation we'd be in with respect to Bionic if we changed our PR jobs to Focal. Maybe that's something we can compensate for with GitHub actions.

the release-branch jobs would still be run on mojave, which is not ideal but would still catch something

GitHub actions supports 10.15 (catalina) and 11.0 (Bug Sur), so I guess we could keep our `ci-pr_any` jobs on 10.14 and just quit early if that package requires 10.15

**Comment by scpeters** [comment]
> > > I would recommend just using catalina for pull request jobs
> > 
> > 
> > That means we would risk breaking Mojave support for Citadel and Dome users, right? I guess that's the same situation we'd be in with respect to Bionic if we changed our PR jobs to Focal. Maybe that's something we can compensate for with GitHub actions.
> 
> the release-branch jobs would still be run on mojave, which is not ideal but would still catch something
> 
> GitHub actions supports 10.15 (catalina) and 11.0 (Bug Sur), so I guess we could keep our `ci-pr_any` jobs on 10.14 and just quit early if that package requires 10.15

moving discussion to https://github.com/ignition-tooling/release-tools/issues/382

**Review by j-rivero — APPROVED** [review]
this is good to go. I'll give a look at #382 , we can probably add some logic somewhere to solve the problem.

**Pull request merged**
