### PR TITLE
Disable ABI checker for ign-cmake and ign-tools

### PR DESCRIPTION
**Pull request by chapulina**
These packages don't have C++ code, so they don't need ABI checking.

### CODE REVIEW

**Comment by scpeters** [comment]
technically, `ign-cmake` has some header files but no library, but I don't think the ABI checker supports this case, so we should disable it

**Comment by j-rivero** [comment]
This PR creates the jobs but disabled. Al alternative approach would be not to create them and save some unnecesary overhead:

```diff
diff --git a/jenkins-scripts/dsl/ignition.dsl b/jenkins-scripts/dsl/ignition.dsl
index 5ee92182..ab1d9b61 100644
--- a/jenkins-scripts/dsl/ignition.dsl
+++ b/jenkins-scripts/dsl/ignition.dsl
@@ -228,6 +228,10 @@ boolean is_a_colcon_package(String ign_software_name)
 ignition_software.each { ign_sw ->
   abi_distro.each { distro ->
     supported_arches.each { arch ->
+      // Packages without ABI 
+      if (ign_sw == 'tools' || ign_sw == 'cmake')
+        return
+
       abi_job_names[ign_sw] = "ignition_${ign_sw}-abichecker-any_to_any-ubuntu_auto-${arch}"
       def abi_job = job(abi_job_names[ign_sw])
       checkout_subdir = "ign-${ign_sw}"
@@ -240,10 +244,6 @@ ignition_software.each { ign_sw ->
         if (ign_sw == 'physics')
           label "huge-memory"
 
-        // Packages without ABI
-        if (ign_sw == 'tools' || ign_sw == 'cmake')
-          disabled()
-
         steps {
           shell("""\
                 #!/bin/bash -xe
```

**Comment by chapulina** [comment]
> This PR creates the jobs but disabled.

Thanks, @j-rivero : eb2843e 

> technically, ign-cmake has some header files but no library

Good point, I don't know what it would take to make that use case work

**Comment by j-rivero** [comment]
Tested here: https://build.osrfoundation.org/view/All/job/_dsl_ignition/1011/console

```
Unreferenced items:
    GeneratedJob{name='ignition_cmake-abichecker-any_to_any-ubuntu_auto-amd64'}
    GeneratedJob{name='ignition_tools-abichecker-any_to_any-ubuntu_auto-amd64'}
Disabled items:
    GeneratedJob{name='ignition_tools-abichecker-any_to_any-ubuntu_auto-amd64'}
    GeneratedJob{name='ignition_cmake-abichecker-any_to_any-ubuntu_auto-amd64'}
Finished: SUCCESS
```

**Pull request merged**
