### PR TITLE
Stable branches for Edifice

### PR DESCRIPTION
**Pull request by chapulina**
Before merging this, we need to:

- [x] Release stable Edifice
- [ ] Bump versions for all `main` branches
- [x] Retire sdf's `master` and use `main` instead (https://github.com/osrf/sdformat/issues/531)
- [x] Create `ign-fortress`

https://github.com/ignition-tooling/release-tools/issues/421

### CODE REVIEW

**Comment by scpeters** [comment]
I updated sdformat.dsl in ae90866

**Comment by chapulina** [comment]
I ran `ignition.dsl` with this branch:

**Comment by chapulina** [comment]
The `ign-edifice` view seems up-to-date:

https://build.osrfoundation.org/view/ign-edifice/

**Comment by chapulina** [comment]
I'll get this in to get things moving, we can make more tweaks in subsequent PRs

**Comment by scpeters** [comment]
the https://build.osrfoundation.org/job/ign-utils1-debbuilder/ job is now disabled since this was merged

**Comment by scpeters** [comment]
> the https://build.osrfoundation.org/job/ign-utils1-debbuilder/ job is now disabled since this was merged

https://github.com/ignition-tooling/release-tools/pull/431

**Pull request merged**
