### PR TITLE
Fix build regression on ign-tools1 for windows on CI

### PR DESCRIPTION
**Pull request by Blast545**
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Comment by Blast545** [comment]
Seems to be fixed: [Build Status](https://build.osrfoundation.org/job/ign_tools-ign-1-win/28/)

**Comment by Blast545** [comment]
@j-rivero I addressed the issue but it took me more attempts with Windows scripting that I expected :roll_eyes:

Can we erase builds from history on https://build.osrfoundation.org/job/ign_tools-ign-1-win/buildTimeTrend?

**Comment by j-rivero** [comment]
> @j-rivero I addressed the issue but it took me more attempts with Windows scripting that I expected roll_eyes

it is a hell to manage, feel your pain.

**Comment by j-rivero** [comment]
Thanks for the PR. I'm afraid that I need some details before reviewing: what problem are we trying to fix (link)?  Why we need this workaround in ign-tools for version 1.x but we don't for others?

**Comment by scpeters** [comment]
> Thanks for the PR. I'm afraid that I need some details before reviewing: what problem are we trying to fix (link)? Why we need this workaround in ign-tools for version 1.x but we don't for others?

the `ign-tools1` branch has a cmake project name without a major version of `ignition-tools`:

https://github.com/ignitionrobotics/ign-tools/blob/ign-tools1/CMakeLists.txt#L3

compare to `ignition-plugin1`:

https://github.com/ignitionrobotics/ign-plugin/blob/ign-plugin1/CMakeLists.txt#L6

the [detect_cmake_major_version.py](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/tools/detect_cmake_major_version.py) doesn't work for `ign-tools1`, which is I think why this is needed

**Comment by scpeters** [comment]
without this branch [Build Status](https://build.osrfoundation.org/job/ign_tools-ign-1-win/21/) https://build.osrfoundation.org/job/ign_tools-ign-1-win/21/

with this branch: [Build Status](https://build.osrfoundation.org/job/ign_tools-ign-1-win/28/) https://build.osrfoundation.org/job/ign_tools-ign-1-win/28/

also `ignition-tools2` with this branch: [Build Status](https://build.osrfoundation.org/job/ign_tools-ci-win/7/) https://build.osrfoundation.org/job/ign_tools-ci-win/7/

**Comment by Blast545** [comment]
@scpeters Thanks a lot for the thorough explanation!

@j-rivero as scpeters said, my main attempt with this PR is addressing the build regression here:
https://build.osrfoundation.org/job/ign_tools-ign-1-win/21/

```
# BEGIN SECTION: colcon compilation with tests for ignition-tools1
"COLCON_EXTRA_ARGS: --packages-select ignition-tools1"
"COLCON_EXTRA_CMAKE_ARGS: " -DBUILD_TESTING=1""
"COLCON_EXTRA_CMAKE_ARGS2: "
[0.954s] colcon.colcon_core.package_selection WARNING ignoring unknown package 'ignition-tools1' in --packages-select

Summary: 0 packages finished [0.33s]
```

This is the portion of code causing the problem:

https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/lib/colcon-default-devel-windows.bat#L32-L36

It happens because the package doesn't have the version as part of its name.

**Comment by j-rivero** [comment]
Thanks for the explanation! Understood.

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
