### PR TITLE
ignition.dsl: enable CI for dome branches

### PR DESCRIPTION
**Pull request by scpeters**
We have release branches now for dome, so enable CI.

Signed-off-by: Steve Peters <scpeters@openrobotics.org>

### CODE REVIEW

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1031/) https://build.osrfoundation.org/job/_dsl_ignition/1031/

**Comment by j-rivero** [comment]
> [Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1031/) https://build.osrfoundation.org/job/_dsl_ignition/1031/

I just hit the cancel button on this one. Sorry but the buildfarm is pretty busy these days and there is another gazebo9 release on the queue so I would prefer to delay these changes until the weekend or next week if possible. Otherwise there will be a good bunch of jobs in the queue which is no good for the RAM consumption.

**Comment by scpeters** [comment]
good point, thanks for stopping it quickly

**Comment by j-rivero** [comment]
> good point, thanks for stopping it quickly

I'm changing this to a draft by now, please reopen it or ping me next week I don't have merged this before

**Comment by scpeters** [comment]
@j-rivero should we test this over the weekend?

**Review by j-rivero — APPROVED** [review]
can not see any problem in the changes. Let's give a run during the weekend and see if more changes are needed.

**Pull request merged**
