### PR TITLE
Migrate vcpkg to use --overlay-ports parameter for osrf/vcpkg-ports

### PR DESCRIPTION
**Pull request by j-rivero**
The PR implements the use of [`--overlay-ports` parameter in vcpkg](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) to inject our custom ogre2 port available at https://github.com/osrf/vcpkg-ports . Until now, the package was manually copied to the ports/ directory.

We don't need the variable `DEPEN_OSRF_PKGS` anymore so I moved all ogre2 references to `DEPEN_PKGS`. The PR still update the master branch of the vcpkg-ports on every installation to catch new changes.

The PR includes a bit of Groovy to display the Updated node for https://build.osrfoundation.org/job/_vcpkg_update_snapshot/.

Tested here: [Build Status](https://build.osrfoundation.org/job/_vcpkg_update_snapshot/9/)

### CODE REVIEW

**Review by chapulina — COMMENTED** [review]
I think you may need to add `ogre2` to `ign-launch` too, which builds on top of all the rest.

Besides this, I didn't notice anything weird. But I don't know anything about vcpkg :wink:

**Review by nuclearsandwich — APPROVED** [review]
I didn't know they'd added an overlay capability. This looks sound. I'd love to see a test build.

**Comment by j-rivero** [comment]
After testing I found that we made some manual modifications to the vcpkg formulas to be able to run without compiling debug packages. Sorry for the extra commits after approval.

* Used this branch to provision windows.local: [Build Status](https://build.osrfoundation.org/job/_vcpkg_update_snapshot/22/)
* Test with rendering is ongoing [Build Status](https://build.osrfoundation.org/job/_test_vcpkg_migration_ign_rendering-ci-win/5/)

**Comment by j-rivero** [comment]
> I think you may need to add `ogre2` to `ign-launch` too, which builds on top of all the rest.

Added all the ones present in ign-gazebo abf7015

**Comment by j-rivero** [comment]
real new testing job: [Build Status](https://build.osrfoundation.org/job/_test_vcpkg_migration_ign_rendering-ci-win/8/)

**Pull request merged**
