### PR TITLE
Build ign-utils from source for sdformat11

### PR DESCRIPTION
**Pull request by azeey**

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by j-rivero** [comment]
Running a test here: [Build Status](https://build.osrfoundation.org/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1502/). Feel free to merge if it is fine.

**Comment by azeey** [comment]
> Running a test here: [Build Status](https://build.osrfoundation.org/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1502/). Feel free to merge if it is fine.

sdformat still uses a master branch, so that build failed. Here's a new one
[Build Status](https://build.osrfoundation.org/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1503/)

**Comment by azeey** [comment]
I didn't see it building ign-utils from source in that last build. I have added more logic in https://github.com/ignition-tooling/release-tools/pull/385/commits/f23d2c3be6c1c15bb4f0107a1338655436eb5e0b. New build: [Build Status](https://build.osrfoundation.org/job/sdformat-ci-pr_any-ubuntu_auto-amd64/1504/)

**Comment by azeey** [comment]
Since I made more changes, do you mind taking another look @chapulina /@j-rivero?

**Review by chapulina — APPROVED** [review]
Nice, I see `ign-utils` being build from source now :+1:

**Comment by chapulina** [comment]
Cross-referencing: https://github.com/osrf/sdformat/pull/474

**Pull request merged**
