### PR TITLE
Edifice nightlies

### PR DESCRIPTION
**Pull request by chapulina**
I'm not sure if this will work, as we didn't have nightlies for `ign-dome` before.

I created these repos copying from Dome:

* https://github.com/ignitionrobotics/ign-edifice
* https://github.com/ignition-release/ign-edifice-release

Is this all that's needed to have `ignition-edifice` nightly debs? Right now, that will be exactly the same as `ignition-dome`, but as we move forward, we'll bump dependencies and this will be updated.

Please advise, @j-rivero . Feel free to directly correct anything I'm missing.

### CODE REVIEW

**Comment by j-rivero** [comment]
Made some fixes, run the first round of nightlies:
 * [Build Status](https://build.osrfoundation.org/job/_dsl_ignition_collection/256/) DSL collection
 * edifice nightly https://build.osrfoundation.org/job/ign-edifice-debbuilder/

Bionic/amd64 and Focal/amd64 are in the repository.

**Review by j-rivero — APPROVED** [review]

**Comment by chapulina** [comment]
Thanks, Jose, your changes look good to me.

**Comment by scpeters** [comment]
I just changed `master` to `main` in #311, so I'll apply those changes here as well

**Comment by scpeters** [comment]
> I just changed `master` to `main` in #311, so I'll apply those changes here as well

372e0b9

**Review by scpeters — APPROVED** [review]

**Pull request merged**
