### PR TITLE
ignition.dsl: colcon for ign-math on windows

### PR DESCRIPTION
**Pull request by mjcarroll**
Part of #412

### CODE REVIEW

**Comment by mjcarroll** [comment]
https://build.osrfoundation.org/job/_dsl_ignition/1235/

**Comment by mjcarroll** [comment]
https://build.osrfoundation.org/job/_dsl_ignition_collection/438/

**Comment by mjcarroll** [comment]
[Build Status](https://build.osrfoundation.org/view/ign-fortress/job/ign_math-ci-win/1/)
[Build Status](https://build.osrfoundation.org/view/ign-edifice/job/ign_math-ign-6-win/1/)

**Comment by mjcarroll** [comment]
after this, need to update:

* [x] ign-math branch protection rules
* [x] build farmer script 
* [x] ign-math README

**Comment by scpeters** [comment]
you may need to set additional variables: https://github.com/ignition-tooling/release-tools/pull/536/files#diff-d7ba6a3389a2d2794f63d288ba91b7075992dbb82355ff0e0b1083177c34ec48R8-R9

testing with this branch:

* [Build Status](https://build.osrfoundation.org/job/ign_math-ci-win/2/) https://build.osrfoundation.org/job/ign_math-ci-win/2/

**Comment by scpeters** [comment]
> [Build Status](https://build.osrfoundation.org/view/ign-fortress/job/ign_math-ci-win/1/) `ign-math7`
> [Build Status](https://build.osrfoundation.org/view/ign-edifice/job/ign_math-ign-6-win/1/) `ign-math6`

the first one of these ran using the `master` branch of release-tools, so it actually ran with configure.bat

**Comment by mjcarroll** [comment]
> you may need to set additional variables: https://github.com/ignition-tooling/release-tools/pull/536/files#diff-d7ba6a3389a2d2794f63d288ba91b7075992dbb82355ff0e0b1083177c34ec48R8-R9

e0f165e

**Comment by mjcarroll** [comment]
Anything else needed here @scpeters ?

**Review by scpeters — APPROVED** [review]

**Pull request merged**
