### PR TITLE
Update ign-common to use colcon

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by scpeters** [comment]
let's deploy this and run some test builds

* [Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1187/) https://build.osrfoundation.org/job/_dsl_ignition/1187/

**Comment by scpeters** [comment]
> let's deploy this and run some test builds
> 
> * [Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1187/) https://build.osrfoundation.org/job/_dsl_ignition/1187/

~~~
Added items:
    GeneratedJob{name='ign_common-pr-win'}
    GeneratedJob{name='ign_common-ign-1-win'}
    GeneratedJob{name='ign_common-ign-3-win'}
    GeneratedJob{name='ign_common-ign-4-win'}
    GeneratedJob{name='ign_common-ci-win'}
...
Unreferenced items:
    GeneratedJob{name='ignition_common-ci-ign-common1-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-ign-common3-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-ign-common4-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-main-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-pr_any-windows7-amd64'}
Disabled items:
    GeneratedJob{name='ignition_common-ci-ign-common4-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-ign-common3-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-ign-common1-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-pr_any-windows7-amd64'}
    GeneratedJob{name='ignition_common-ci-main-windows7-amd64'}
~~~

looks good so far

**Comment by scpeters** [comment]
test builds:

* [Build Status](https://build.osrfoundation.org/job/ign_common-ign-3-win/1/) https://build.osrfoundation.org/job/ign_common-ign-3-win/1/
* [Build Status](https://build.osrfoundation.org/job/ign_common-ign-4-win/1/) https://build.osrfoundation.org/job/ign_common-ign-4-win/1/

**Comment by mjcarroll** [comment]
I think yellow on common4 is probably expected, since that branch hasn't been tested in some time.

**Comment by scpeters** [comment]
I think we need to add an ign-common1.yaml file to gazebodistro

* [Build Status](https://build.osrfoundation.org/job/ign_common-ign-1-win/1/) https://build.osrfoundation.org/job/ign_common-ign-1-win/1/

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/ign_common-ci-win/1/) https://build.osrfoundation.org/job/ign_common-ci-win/1/

**Comment by scpeters** [comment]
> I think yellow on common4 is probably expected, since that branch hasn't been tested in some time.

it ran fine on Sept 10: [Build Status](https://build.osrfoundation.org/job/ignition_common-ci-ign-common4-windows7-amd64/11/) https://build.osrfoundation.org/job/ignition_common-ci-ign-common4-windows7-amd64/11/

I'm guessing it may be an issue with the machine it ran on? https://build.osrfoundation.org/computer/(not%20in%20service)%20windows_mad.win32/

**Comment by mjcarroll** [comment]
> I think we need to add an ign-common1.yaml file to gazebodistro

https://github.com/ignition-tooling/gazebodistro/pull/44

**Comment by mjcarroll** [comment]
> it ran fine on Sept 10

All of the failing tests come from the `graphics` component, which was getting skipped as `ign-utils1` wasn't being installed on Windows: 

```
CMake Warning at C:/Jenkins/workspace/ignition_common-ci-ign-common4-windows7-amd64/ws/install/share/cmake/ignition-cmake2/cmake2/IgnConfigureBuild.cmake:53 (message):
   CONFIGURATION WARNINGS:
   -- Skipping component [graphics]: Missing dependency [ignition-utils1].
      ^~~~~ Set SKIP_graphics=true in cmake to suppress this warning.
```

**Comment by scpeters** [comment]
> > I think we need to add an ign-common1.yaml file to gazebodistro
> 
> [ignition-tooling/gazebodistro#44](https://github.com/ignition-tooling/gazebodistro/pull/44)

I think this PR will be fine to merge once ignition-tooling/gazebodistro#44 gets in

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
> I'm guessing it may be an issue with the machine it ran on? https://build.osrfoundation.org/computer/(not%20in%20service)%20windows_mad.win32/

both unstable builds that I posted ran on `windows_mad.win32`

I've taken it offline and restarted one to see if it is an issue with the build machine

* [Build Status](https://build.osrfoundation.org/job/ign_common-ign-4-win/2/) https://build.osrfoundation.org/job/ign_common-ign-4-win/2/

**Comment by j-rivero** [comment]
Changes looks good to me. We need to give a shoot to the buildfarmers to update the dashboard https://github.com/osrf/buildfarmer/blob/main/Ignition.md after merging this PR.

**Comment by scpeters** [comment]
> > I'm guessing it may be an issue with the machine it ran on? https://build.osrfoundation.org/computer/(not%20in%20service)%20windows_mad.win32/
> 
> both unstable builds that I posted ran on `windows_mad.win32`
> 
> I've taken it offline and restarted one to see if it is an issue with the build machine
> 
> * [Build Status](https://build.osrfoundation.org/job/ign_common-ign-4-win/2/) https://build.osrfoundation.org/job/ign_common-ign-4-win/2/

unstable builds look like a problem with https://build.osrfoundation.org/computer/(not%20in%20service)%20windows_mad.win32/

**Comment by scpeters** [comment]
> Changes looks good to me. We need to give a shoot to the buildfarmers to update the dashboard https://github.com/osrf/buildfarmer/blob/main/Ignition.md after merging this PR.

also need to update the required CI job names in ign-common's GitHub branch settings

**Comment by mjcarroll** [comment]
* [Build Status](https://build.osrfoundation.org/job/ign_common-ign-1-win/2/) https://build.osrfoundation.org/job/ign_common-ign-1-win/2/

**Comment by mjcarroll** [comment]
> We need to give a shoot to the buildfarmers to update the dashboard https://github.com/osrf/buildfarmer/blob/main/Ignition.md after merging this PR.

https://github.com/osrf/buildfarmer/pull/228

**Comment by mjcarroll** [comment]
> also need to update the required CI job names in ign-common's GitHub branch settings

Done.

**Pull request merged**
