### PR TITLE
Add README with release instructions

### PR DESCRIPTION
**Pull request by chapulina**
Includes part of the README from #333.

Document the release process, step-by-step.

### CODE REVIEW

**Review by j-rivero — APPROVED** [review]
great!

**Review by JShep1 — COMMENTED** [review]
This is pretty good and got me most of the way there as a no-knowledge of releases person.  I have a couple questions, are these steps intended to be executed immediately after another?  Does the PR from step 1 need to be approved before you can continue to step 2?  When should the actual release be triggered?

Additionally, I'm going to add a sentence or two adding a little bit more explanation for updating the changelog.

**Comment by chapulina** [comment]
Thanks for the tweaks, @JShep1 . I think I addressed your questions in 6b76194, let me know what you think.

**Comment by JShep1** [comment]
> Thanks for the tweaks, @JShep1 . I think I addressed your questions in [6b76194](https://github.com/ignition-tooling/release-tools/commit/6b761941ba15d94962d2b3e667d2a74b4be6ac47), let me know what you think.

Looks good!  I added a few updates here 99e006896cf250151d6e01809e9ec10c55e8c164 .  You can modify them how you see fit.

**Review by JShep1 — APPROVED** [review]

**Comment by chapulina** [comment]
Thanks, @JShep1 . I did some final tweaks in bbc0de0, now merging!

**Pull request merged**
