### PR TITLE
ignition_collection.dsl: add Garden view

### PR DESCRIPTION
**Pull request by scpeters**
Part of #527. Just copied the contents of the Fortress view to Garden.

testing: [Build Status](https://build.osrfoundation.org/job/_dsl_ignition_collection/414/) https://build.osrfoundation.org/job/_dsl_ignition_collection/414/

https://build.osrfoundation.org/view/ign-garden/

### CODE REVIEW

**Comment by scpeters** [comment]
at first I thought just to add the view, but it's a trivial change to switch the nightlies to Garden since all the package versions are the same, so I made that change as well in https://github.com/ignition-tooling/release-tools/pull/546/commits/93618ebbc9524cfb5e207b1624aebdc381f6bc32

**Comment by scpeters** [comment]
> at first I thought just to add the view, but it's a trivial change to switch the nightlies to Garden since all the package versions are the same, so I made that change as well in [93618eb](https://github.com/ignition-tooling/release-tools/commit/93618ebbc9524cfb5e207b1624aebdc381f6bc32)

[Build Status](https://build.osrfoundation.org/job/_dsl_ignition_collection/415/) https://build.osrfoundation.org/job/_dsl_ignition_collection/415/

**Comment by scpeters** [comment]
[Build Status](https://build.osrfoundation.org/job/ignition-garden-nightly-scheduler/1/) https://build.osrfoundation.org/job/ignition-garden-nightly-scheduler/1/

**Review by j-rivero — APPROVED** [review]

**Comment by j-rivero** [comment]
Found a problem with fortress job inside the garden view, I think it is fixed by 2f18a50

**Comment by scpeters** [comment]
thanks!

**Pull request merged**
