### PR TITLE
Add python3-distutils to IGN_MATH_DEPENDENCIES

### PR DESCRIPTION
**Pull request by j-rivero**
Should fix problems on CI in https://github.com/ignitionrobotics/ign-math/pull/360

Tested [Build Status](https://build.osrfoundation.org/job/ignition_math-ci-pr_any-ubuntu_auto-amd64/1190/)

### CODE REVIEW

**Comment by chapulina** [comment]
Thanks! I added that to `ign-math`'s `packages.apt` together with the rest of dependencies in https://github.com/ignitionrobotics/ign-math/pull/360. That's a better place for it since it's used by GitHub actions, tutorials, etc.

**Comment by scpeters** [comment]
> Thanks! I added that to `ign-math`'s `packages.apt` together with the rest of dependencies in [ignitionrobotics/ign-math#360](https://github.com/ignitionrobotics/ign-math/pull/360). That's a better place for it since it's used by GitHub actions, tutorials, etc.

agreed. I proposed moving away from storing dependency information in `dependencies_archive.sh` in #619 since it is easier to express the logic for different versions and OS combinations with the `packages.apt` files

**Comment by j-rivero** [comment]
> agreed. I proposed moving away from storing dependency information in `dependencies_archive.sh` in #619 since it is easier to express the logic for different versions and OS combinations with the `packages.apt` files

ack. I think that we have discussed this in the past, moving dependencies to a more distributed approach could be easier to manage in the short term but it comes with the cost of increasing maintenance effort for changing affecting multiple versions. No silver bullet here.

Do we have a tracking issue to check the status of the migration effort?

**Comment by chapulina** [comment]
> I think that we have discussed this in the past

I think this issue is related, I'll add a comment there: https://github.com/ignition-tooling/release-tools/issues/190

**Comment by j-rivero** [comment]
This is now added in https://github.com/ignitionrobotics/ign-math/blob/ign-math6/.github/ci/packages.apt#L3. Closing.

**Pull request closed without merging**
