### PR TITLE
Force vcs import to make possible change between forks

### PR DESCRIPTION
**Pull request by j-rivero**
While testing an external contributor PR, `vcs import` was complaning about reusing source code that belongs to other repository, which was true since I was using a fork of our ign-cmake repository.

To always override the sources, I added the `--force` parameter which is exactly for that.

### CODE REVIEW

**Review by Blast545 — APPROVED** [review]

**Comment by Blast545** [comment]
Will this address the error in these?

https://build.osrfoundation.org/job/ign_gazebo-pr-win/3455
https://build.osrfoundation.org/job/ign_gazebo-pr-win/3454

I just saw them, I imagined it was related to cleaning part of the environment.

**Comment by j-rivero** [comment]
> Will this address the error in these?
> 
> https://build.osrfoundation.org/job/ign_gazebo-pr-win/3455 https://build.osrfoundation.org/job/ign_gazebo-pr-win/3454
> 
> I just saw them, I imagined it was related to cleaning part of the environment.

I think so, `Path already exists and contains a different repository` is the error message. Let's merge this now.

**Comment by Blast545** [comment]
FYI, I tried rerunning a pr job and got the same error I was mentioning, so maybe it's unrelated to the fix you were targetting:
https://build.osrfoundation.org/job/ign_gazebo-pr-win/3458/console

**Comment by j-rivero** [comment]
> FYI, I tried rerunning a pr job and got the same error I was mentioning, so maybe it's unrelated to the fix you were targetting:

different error:
```
Invocation of command 'import' on client 'git' failed: PermissionError: [WinError 5] Access is denied: 'C:\\Jenkins\\workspace\\ign_gazebo-pr-win\\ws\\ign-cmake' (c:\program files\python38\lib\site-packages\vcstool\clients\git.py:242)
```

**Pull request merged**
