### PR TITLE
Implement --only-bump-revision-linux in release.py

### PR DESCRIPTION
**Pull request by j-rivero**
The PR adds the `--only-bump-revision-linux` that allows to call Jenkins on revision bumps (those only changing build metadata no source code from the application) without uploading tarballs.

The current code is a bit messy and to get the tarball name that was finally uploaded in the first time it is needed to generate locally the tarball, although it is not finally uploaded. 

recommendation: enable w=1 to see differences in code https://github.com/ignition-tooling/release-tools/pull/394/files?w=1

### CODE REVIEW

**Comment by scpeters** [comment]
I think this will conflict with #393, which should we review first?

**Comment by j-rivero** [comment]
> I think this will conflict with #393, which should we review first?

Don't have any preference. Since we have already started with #393 , let's finish it first.

**Comment by chapulina** [comment]
I haven't looked at the code, but I just used this branch to trigger `ign-transport10.0.0~pre2-2` I think it worked, but I see the `tar` line, which I'm not sure should be there.

```
Running:
  tar xf /tmp/tmpfs3q49t8/orig.tar -C /tmp/tmpfs3q49t8/src
```

**Comment by scpeters** [comment]
> I haven't looked at the code, but I just used this branch to trigger `ign-transport10.0.0~pre2-2` I think it worked, but I see the `tar` line, which I'm not sure should be there.
> 
> ```
> Running:
>   tar xf /tmp/tmpfs3q49t8/orig.tar -C /tmp/tmpfs3q49t8/src
> ```

did you see the following message in the console output:

~~~
INFO: bump revision is enabled. It needs to generate a local tarball although it will not upload it
~~~

**Comment by j-rivero** [comment]
> > ```
> > 
> > ```
> 
> 
> did you see the following message in the console output:

not sure if we can improve the message or user information in any other way. Seems like it worked well, @chapulina ?

**Comment by chapulina** [comment]
> did you see the following message in the console output:

I didn't notice it, but it may have been there.

> Seems like it worked well,

Yup, AFAICT it worked perfectly :+1:

**Pull request merged**
