### PR TITLE
Make Windows build use Ogre 2.2

### PR DESCRIPTION
**Pull request by mjcarroll**
Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by mjcarroll** [comment]
Giving this a spin: https://build.osrfoundation.org/job/ign_rendering-pr-win/1484/console

**Comment by j-rivero** [comment]
Running a new test with conditional in [Build Status](https://build.osrfoundation.org/job/ign_rendering-pr-win/1488/). If that works we need to use in the rest of modified files in this PR.

**Comment by j-rivero** [comment]
Not sure how we want to proceed with Ogre-2.2 on Windows (not sure if it is stopped now or that was only Mac), @mjcarroll should we work on merging this?

**Comment by chapulina** [comment]
> (not sure if it is stopped now or that was only Mac)

My understanding is that it's already working on Windows, so we're planning to support it.

**Comment by j-rivero** [comment]
Ok, I think this is ready for reviewing:

[Build Status](https://build.osrfoundation.org/job/ign_rendering-pr-win/1577/) . Job is failing but ogre-2.2 is going into the mix successfully. Problem finding Ogre2 header:

```
C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\ogre2\include\ignition/rendering/ogre2/Ogre2Includes.hh(43,10): fatal error C1083: Cannot open include file: 'OgreImage2.h'
```

**Review by j-rivero — APPROVED** [review]

**Comment by j-rivero** [comment]
Final test: [Build Status](https://build.osrfoundation.org/job/ign_rendering-pr-win/1697/)

**Pull request merged**
