### PR TITLE
ign_common windows: use gdal

### PR DESCRIPTION
**Pull request by scpeters**
Needed by https://github.com/ignitionrobotics/ign-rendering/pull/539

### CODE REVIEW

**Comment by scpeters** [comment]
testing: [Build Status](https://build.osrfoundation.org/view/ign-garden/job/ign_common-ci-win/13/) https://build.osrfoundation.org/view/ign-garden/job/ign_common-ci-win/13/

~~~
# BEGIN SECTION: install external dependency gdal
"VCPKG_HEAD is 2021.05.12"
From https://github.com/osrf/vcpkg-ports
 * branch            master     -> FETCH_HEAD
Already up to date.
Computing installation plan...
The following packages will be rebuilt:
  * qt5-activeqt[core]:x64-windows -> 5.15.2
  * qt5-base[core]:x64-windows -> 5.15.2#8
  * qt5-declarative[core]:x64-windows -> 5.15.2
  * qt5-imageformats[core]:x64-windows -> 5.15.2
  * qt5-multimedia[core]:x64-windows -> 5.15.2
  * qt5-networkauth[core]:x64-windows -> 5.15.2
  * qt5-quickcontrols2[core]:x64-windows -> 5.15.2
  * qt5-svg[core]:x64-windows -> 5.15.2
  * qt5-tools[core]:x64-windows -> 5.15.2
  * qt5-winextras[core]:x64-windows -> 5.15.2
  * sqlite3[core,tool]:x64-windows -> 3.35.4
The following packages will be built and installed:
  * cfitsio[core]:x64-windows -> 3.49
  * expat[core]:x64-windows -> 2020-08-18
    gdal[core]:x64-windows -> 3.2.2
  * geos[core]:x64-windows -> 3.9.1
  * giflib[core]:x64-windows -> 5.1.4-6
  * hdf5[core,szip,zlib]:x64-windows -> 1.12.0#2
  * libgeotiff[core]:x64-windows -> 1.6.0#2
  * libpq[core,openssl,zlib]:x64-windows -> 12.2#16
  * netcdf-c[core]:x64-windows -> 4.7.4#2
  * proj4[core,database,tiff]:x64-windows -> 7.2.1#2
  * szip[core]:x64-windows -> 2.1.1-6
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run the command with the --recurse option
Failed with error #1.
~~~

**Review by chapulina — COMMENTED** [review]
ign-physics and ign-gazebo should also need it

**Comment by scpeters** [comment]
> ign-physics and ign-gazebo should also need it

I think everything that depends on ign-physics and ign-rendering will need it; so we'll have to add a bit more

do we want a `.github/ci/packages.vcpkg` file in each repository?

**Comment by chapulina** [comment]
> do we want a .github/ci/packages.vcpkg file in each repository?

I think it depends on when we plan to tackle 

* https://github.com/ignition-tooling/release-tools/issues/373

**Comment by j-rivero** [comment]
> Additional packages (*) will be modified to complete this operation.
> If you are sure you want to rebuild the above packages, run the command with the --recurse option
> Failed with error #1.

Looks to me that `vcpkg` refuses to recompile/reinstall packages without the `--recurse` option. Probably because some of them will be installed in a different way (more/different components). I can not see any risk on trying to add that option to the install command.

**Comment by scpeters** [comment]
> > Additional packages (*) will be modified to complete this operation.
> > If you are sure you want to rebuild the above packages, run the command with the --recurse option
> > Failed with error #1.
> 
> Looks to me that `vcpkg` refuses to recompile/reinstall packages without the `--recurse` option. Probably because some of them will be installed in a different way (more/different components). I can not see any risk on trying to add that option to the install command.

ok, let's try it: https://github.com/ignition-tooling/release-tools/pull/624/commits/78d153a00f0e83cd311fe248d7e56cbfb7896e2a

**Comment by scpeters** [comment]
testing again [Build Status](https://build.osrfoundation.org/view/ign-garden/job/ign_common-ci-win/14/) https://build.osrfoundation.org/view/ign-garden/job/ign_common-ci-win/14/

**Comment by scpeters** [comment]
> > ign-physics and ign-gazebo should also need it
> 
> I think everything that depends on ign-physics and ign-rendering will need it; so we'll have to add a bit more

I've added the dependency to all garden dependents of ign-physics and ign-rendering in https://github.com/ignition-tooling/release-tools/pull/624/commits/0bf9af52b9def892644855557ba4838615d02e69

I think this is ready for review

**Review by j-rivero — APPROVED** [review]
Looks good to me

**Pull request merged**
