### PR TITLE
Disable CI for ign-rndf

### PR DESCRIPTION
**Pull request by scpeters**
ign-rndf CI is failing as it doesn't have a main branch, but it has been inactive for a while; I propose to disable its CI jobs.

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
@caguero , should we archive https://github.com/ignitionrobotics/ign-rndf/ ?

**Comment by caguero** [comment]
I think it's OK to disable CI, but I'd leave the repo available just in case someone is using it out there.

**Comment by scpeters** [comment]
> I think it's OK to disable CI, but I'd leave the repo available just in case someone is using it out there.

archived repositories can still be cloned and forked; I think the main thing missing is being able to open and comment on issues

**Comment by scpeters** [comment]
I'll merge this now, but discussion can continue about the archiving question

**Pull request merged**
