### PR TITLE
Restrict gazebo build to large-memory nodes

### PR DESCRIPTION
**Pull request by j-rivero**
Main motivation to change is that when a gazebo-ci-pr_any-none is being build in a non powerful node, that build can last for hours with the undesired side effect of blocking backup in some ocassions. The PR restrict the builds to the most powerful nodes. As a downside: we can fall into the scenario where gazebo builds are in the queue but the a non-powerful node is available.

Other small changes in this PR: standardize the label for gpu nodes using gpu-reliable instead some other old formulas.

### CODE REVIEW

**Comment by j-rivero** [comment]
Found some missing definitions by running locally:
```
jrivero@nium dsl $ (gazebo_build_labels) jentest gazebo.dsl 
...
jrivero@nium dsl $ (gazebo_build_labels) grep assigned *.xml  | grep docker
gazebo10-debbuilder.xml:    <assignedNode>docker</assignedNode>
gazebo11-debbuilder.xml:    <assignedNode>docker</assignedNode>
gazebo7-debbuilder.xml:    <assignedNode>docker</assignedNode>
gazebo9-debbuilder.xml:    <assignedNode>docker</assignedNode>
```

**Comment by scpeters** [comment]
conflicts

**Comment by j-rivero** [comment]
I've modified the changes to include gpu tag together with large memory when needed. I've left out the installations and abi-checker. Local run and grep:

```xml
jrivero@nium dsl $ (gazebo_build_labels) grep -R large-memory *.xml
gazebo-abichecker-any_to_any-ubuntu_auto-amd64.xml:    <assignedNode>large-memory</assignedNode>
gazebo-ci_BTCoverage-master-bionic-amd64-gpu-none.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci_BTDebug-master-bionic-amd64-gpu-none.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci_BTRelease-master-bionic-amd64-gpu-none.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-coverage-bionic-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-gazebo10-xenial-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-gazebo11-bionic-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-gazebo7-xenial-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-gazebo9-xenial-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-master-bionic-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-master-bionic-i386-gpu-none.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-pr_any+sdformat_any+ign_any-xenial-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-ci-pr_any-ubuntu_auto-amd64-gpu-nvidia.xml:    <assignedNode>gpu-reliable &amp;&amp; large-memory</assignedNode>
gazebo-install-gazebo10_pkg-xenial-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install-gazebo11_pkg-bionic-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install-gazebo7_pkg-xenial-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install-gazebo9_pkg-xenial-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install-one_liner-bionic-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install-one_liner-xenial-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install_ubuntu_official-gazebo7_pkg-xenial-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>
gazebo-install_ubuntu_official-gazebo9_pkg-bionic-amd64.xml:    <assignedNode>gpu-reliable</assignedNode>

```

**Review by scpeters — APPROVED** [review]

**Comment by scpeters** [comment]
let's test this before merging to make sure the syntax is ok

**Comment by scpeters** [comment]
looks good to me:

* https://build.osrfoundation.org/job/_dsl_gazebo/748/console
* https://build.osrfoundation.org/label/gpu-reliable&&large-memory/

**Pull request merged**
