### PR TITLE
New script to create multipe -release repos for new Ignition releases

### PR DESCRIPTION
**Pull request by j-rivero**
Some bash lines to make our life easier when changing to a new version of Ignition collections. What it does:

 1. Create ign-fooY-release if it does not exits
 1. Clone to the current directory
 1. Pull from main/master branch from previous version, ign-fooX-release repository to have the whole history
 1. Run the  bump_major_version from X to Y
 1. Show the results
 1. commit/push all the changes

I've used it to create https://github.com/ignition-release/ign-fuel-tools6-release using:

```bash
~/code/release-tools/release-repo-scripts/new_ignition_release_repos.bash ign-fuel-tools6
```
Multiple space separated arguments can be passed. It requires that the user has the awesome https://github.com/cli/cli installed and configured.

### CODE REVIEW

**Comment by chapulina** [comment]
It would be nice to add some notes on the top of the file explaining where it should be run. I tried running directly from `release-tools` and got:

```
release-tools$ ./release-repo-scripts/new_ignition_release_repos.bash ign-gui5
Procesing ign-gui5
 + creating the repository 
✓ Created repository ignition-release/ign-gui5-release on GitHub
fatal: remote origin already exists.
git: exit status 128
```

Then I tried from `ign-gui4-release`:

```
ign-gui4-release$ ../release-tools/release-repo-scripts/new_ignition_release_repos.bash ign-gui5
Procesing ign-gui5
 + creating the repository 
  ? repository ignition-release/ign-gui5-release already exists!. Is it empty?
   + ign-gui5-release is empty
 + pull from previous version ignition-release/ign-gui4-release
remote: Enumerating objects: 196, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 196 (delta 47), reused 187 (delta 42), pack-reused 0
Receiving objects: 100% (196/196), 20.01 KiB | 20.01 MiB/s, done.
Resolving deltas: 100% (47/47), done.
From github.com:ignition-release/ign-gui4-release
 * [new branch]      master     -> previous/master
 + run bump_major_version script 4 -> 5

 -------------------------------
../release-tools/release-repo-scripts/new_ignition_release_repos.bash: line 84: ../release-tools/release-repo-scripts/bump_major_version.bash: No such file or directory
```

**Comment by j-rivero** [comment]
> It would be nice to add some notes on the top of the file explaining where it should be run.

It should be able to work from any location, it's going to create the -release repositories in the current directory thought.

> release-tools$ ./release-repo-scripts/new_ignition_release_repos.bash ign-gui5
> Procesing ign-gui5
>  + creating the repository 
> ✓ Created repository ignition-release/ign-gui5-release on GitHub
> fatal: remote origin already exists.
> git: exit status 128

ugh I don't know where the error come from. Could you please run it with `bash -x ./release-repo-scripts/new_ignition_release_repos.bash ign-gui5` and paste the output?

> ../release-tools/release-repo-scripts/new_ignition_release_repos.bash: line 84: ../release-tools/release-repo-scripts/bump_major_version.bash: No such file or directory

This should be fixed in 19672b4 . Would you mind try again?

**Review by chapulina — APPROVED** [review]
It's working great now! I created these repos:

* https://github.com/ignition-release/ign-gazebo5-release
* https://github.com/ignition-release/ign-gui5-release

Will create the remaining ones now too.

**Comment by chapulina** [comment]
I got the `remote origin already exists` error again:

```
$ bash -x ./release-repo-scripts/new_ignition_release_repos.bash ign-cmake3
+ set -e
+++ dirname ./release-repo-scripts/new_ignition_release_repos.bash
++ cd ./release-repo-scripts
++ pwd -P
+ SCRIPT_DIR=/tmp/bump_dependency/release-tools/release-repo-scripts
+ [[ 1 -lt 1 ]]
+ NEW_REPOS=ign-cmake3
+ for repo_name in ${NEW_REPOS}
+ echo 'Procesing ign-cmake3'
Procesing ign-cmake3
+ repo_fname=ign-cmake3-release
+ repo_github=ignition-release/ign-cmake3-release
+ echo ' + creating the repository '
 + creating the repository 
+ [[ -d ign-cmake3-release ]]
++ repo_exists ignition-release/ign-cmake3-release
++ local repo_github=ignition-release/ign-cmake3-release
++ gh repo view ignition-release/ign-cmake3-release
++ echo false
+ false
+ gh repo create --confirm --public --enable-issues --description 'Debian/Ubuntu metadata for ign-cmake3' ignition-release/ign-cmake3-release
✓ Created repository ignition-release/ign-cmake3-release on GitHub
fatal: remote origin already exists.
git: exit status 128
```

Running it a 2nd time goes further, but stops at:

```
+ /tmp/bump_dependency/release-tools/release-repo-scripts/bump_major_version.bash 2 3
Not found a single install file with the old_version number
```

I think `ign-cmake` may be a special snowflake.

**Comment by chapulina** [comment]
I also noticed that the script is creating `master` branches for the new repos, even though GitHub now defaults to `main`.

**Pull request merged**
