### PR TITLE
Install dependencies defined on packages.apt file in source code 

### PR DESCRIPTION
**Pull request by chapulina**
Related tickets: https://github.com/ignition-tooling/release-tools/issues/190 / https://github.com/ignition-tooling/action-ignition-ci/pull/15 / https://github.com/ignition-tooling/release-tools/pull/316

All Ignition libraries now have `.github/ci/package*.apt` files in their source code defining all their debian dependencies. An elaborate example is `ign-gazebo`, which has [3 packages files](https://github.com/ignitionrobotics/ign-gazebo/tree/main/.github/ci):

* `packages.apt` for dependencies common to all platforms
* `packages-bionic.apt` for dependencies specific to Bionic
* `packages-focal.apt` for dependencies specific to Focal

These files are being used by the GitHub actions CI in https://github.com/ignition-tooling/action-ignition-ci , and we can use them here too. Having these files living next to the source code make it easier to update dependencies at the same time as the source code changes.

Nothing is broken if a library doesn't have `packages.apt` files.

This was tested [here](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64/431/console), see how the packages listed [here](https://github.com/ignitionrobotics/ign-fuel-tools/blob/main/.github/ci/packages.apt) ended up in the `PACKAGES_CACHE_AND_CHECK_UPDATES` variable.

With this change, I think we don't need to keep [dependencies_archive.sh](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/lib/dependencies_archive.sh) updated whenever dependencies are added to Ignition libraries anymore? Not sure if that's used for something other than CI.

### CODE REVIEW

**Comment by scpeters** [comment]
how do you feel about re-adding #305 into this PR so we can test that it's working?

**Comment by scpeters** [comment]
I like storing this metadata in the repository much better than in `dependencies_archive.sh`, so I think this is a great idea; I'd just like to incorporate the changes from #305 and run a bunch of release branch CI jobs using this branch

**Comment by chapulina** [comment]
This branch doesn't include #316 , so the test mentioned above is still at a state where #305 was in: https://build.osrfoundation.org/job/ignition_fuel-tools-ci-pr_any-ubuntu_auto-amd64/431/console

I'll add those changes here again just in case.

**Comment by chapulina** [comment]
Updated this branch and reverted #316 .

Triggered new build for https://github.com/ignitionrobotics/ign-transport/pull/188, which this is meant to fix:

[Build Status](https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-ubuntu_auto-amd64/488/)

**Comment by chapulina** [comment]
> run a bunch of release branch CI jobs using this branch

Just saw you said a bunch, so here we go:

* Version without `packages.apt`: `ign-math5` [Build Status](https://build.osrfoundation.org/job/ignition_math-ci-ign-math5-bionic-amd64/19/)
* Blueprint version: `ign-rendering2`: [Build Status](https://build.osrfoundation.org/job/ignition_rendering-ci-ign-rendering2-bionic-amd64/38/)
* Version used in multiple collections: `ign-common3`: [Build Status](https://build.osrfoundation.org/job/ignition_common-ci-ign-common3-bionic-amd64/61/)

**Comment by scpeters** [comment]
ok, I should have said, "let's test all the dome jobs whose build scripts were affected by #305", so the ign-transport build is a good one, but I'd like to test the others too. I'll start them and post build badges

**Comment by scpeters** [comment]
> ok, I should have said, "let's test all the dome jobs whose build scripts were affected by #305", so the ign-transport build is a good one, but I'd like to test the others too. I'll start them and post build badges

* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_fuel-tools-ci-ign-fuel-tools5-bionic-amd64/2/) https://build.osrfoundation.org/view/ign-dome/job/ignition_fuel-tools-ci-ign-fuel-tools5-bionic-amd64/2/
* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_gazebo-ci-ign-gazebo4-bionic-amd64/3/) https://build.osrfoundation.org/view/ign-dome/job/ignition_gazebo-ci-ign-gazebo4-bionic-amd64/3/
* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_gui-ci-ign-gui4-bionic-amd64/2/) https://build.osrfoundation.org/view/ign-dome/job/ignition_gui-ci-ign-gui4-bionic-amd64/2/
* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_launch-ci-ign-launch3-bionic-amd64/2/) https://build.osrfoundation.org/view/ign-dome/job/ignition_launch-ci-ign-launch3-bionic-amd64/2/
* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_rendering-ci-ign-rendering4-bionic-amd64/3/) https://build.osrfoundation.org/view/ign-dome/job/ignition_rendering-ci-ign-rendering4-bionic-amd64/3/

* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_sensors-ci-ign-sensors4-bionic-amd64/2/) https://build.osrfoundation.org/view/ign-dome/job/ignition_sensors-ci-ign-sensors4-bionic-amd64/2/
* [Build Status](https://build.osrfoundation.org/view/ign-dome/job/ignition_transport-ci-ign-transport9-bionic-amd64/2/) https://build.osrfoundation.org/view/ign-dome/job/ignition_transport-ci-ign-transport9-bionic-amd64/2/

**Review by scpeters — APPROVED** [review]

**Pull request merged**
