### PR TITLE
Migrate fuel tools windows build to colcon

### PR DESCRIPTION
**Pull request by j-rivero**
:farmer:  To solve the failing of ci windows on main I just moved the build to colcon (part of #412) 

Before: [Build Status](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-main-windows7-amd64/19/)

After: [Build Status](https://build.osrfoundation.org/job/ignition_fuel-tools-ci-main-windows7-amd64/20/)

The PR includes a fix for all SCRIPT_DIR variables, Windows does not like quotes.

### CODE REVIEW

**Comment by chapulina** [comment]
Nice! Does this mean we can remove https://github.com/ignitionrobotics/ign-fuel-tools/blob/ign-fuel-tools6/configure.bat ?

**Comment by j-rivero** [comment]
> Nice! Does this mean we can remove https://github.com/ignitionrobotics/ign-fuel-tools/blob/ign-fuel-tools6/configure.bat ?

not fully sure since the configure.bat machinery of reverse-dependencies using ign-fuel-tools call be using it via [install_ign_project](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/lib/windows_library.bat#L115-L135).  Best thing should be complete the transition and kill all configure.bat files.

**Comment by scpeters** [comment]
we don't need to update the `dsl`?

**Review by chapulina — APPROVED** [review]

**Comment by j-rivero** [comment]
> we don't need to update the `dsl`?

$deity preserves your memory for decades. 127551d . Used to have shorter names and avoid the max length on windows using cmd.exe.

**Comment by scpeters** [comment]
> > we don't need to update the `dsl`?
> 
> $deity preserves your memory for decades. [127551d](https://github.com/ignition-tooling/release-tools/commit/127551d32fde42dd541481247187e62781974453) . Used to have shorter names and avoid the max length on windows using cmd.exe.

testing dsl: [Build Status](https://build.osrfoundation.org/job/_dsl_ignition/1132/) https://build.osrfoundation.org/job/_dsl_ignition/1132/

**Comment by scpeters** [comment]
~~~
Added items:
    GeneratedJob{name='ign_fuel-tools-pr-win'}
    GeneratedJob{name='ign_fuel-tools-ign-1-win'}
    GeneratedJob{name='ign_fuel-tools-ign-4-win'}
    GeneratedJob{name='ign_fuel-tools-ign-5-win'}
    GeneratedJob{name='ign_fuel-tools-ign-6-win'}
    GeneratedJob{name='ign_fuel-tools-ci-win'}
...
Unreferenced items:
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools1-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools4-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools5-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools6-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-main-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-pr_any-windows7-amd64'}
Disabled items:
    GeneratedJob{name='ignition_fuel-tools-ci-main-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-pr_any-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools1-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools6-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools5-windows7-amd64'}
    GeneratedJob{name='ignition_fuel-tools-ci-ign-fuel-tools4-windows7-amd64'}
~~~

* [Build Status](https://build.osrfoundation.org/job/ign_fuel-tools-ign-5-win/1/) https://build.osrfoundation.org/job/ign_fuel-tools-ign-5-win/1/

we need to make sure there are gazebodistro files for all the major versions we are supporting

**Comment by j-rivero** [comment]
> we need to make sure there are gazebodistro files for all the major versions we are supporting

https://github.com/osrf/buildfarmer/pull/177

**Comment by j-rivero** [comment]
remember to merge https://github.com/osrf/buildfarmer/pull/177 together with this

**Comment by scpeters** [comment]
> > we need to make sure there are gazebodistro files for all the major versions we are supporting
> 
> is fuel-tools1 still supported? I think is the only missing from the list.

fuel-tools1 in https://github.com/ignition-tooling/gazebodistro/pull/34

**Review by scpeters — APPROVED** [review]

**Comment by j-rivero** [comment]
Together with @ahcorde we tested this in [Build Status](https://build.osrfoundation.org/job/ign_fuel-tools-pr-win/1/) . Seems to work perfectly.

**Pull request merged**
